---
  - name: "My first playbook"
    hosts: localhost
    tasks:
      - name: "test reachability"
        ping:

      - name: "display files attributes"
        find: 
          path: /home/vagrant/ANSIBLE 
          file_type: file
          patterns: "*.txt"
