---
# tasks file for create_user
- name: create remote user
  user: 
    name: '{{user_name}}'
    state: '{{user_state}}'
    shell: '{{default_shell}}'
    groups: sudo
    append: yes
    create_home: yes

- name: remove user folder
  file:
    path: '/home/{{user_name}}'
    state: '{{user_state}}'
  when: user_state == "absent"
