---
- name: INIT TASKS FOR ALL MACHINES
  hosts: all:&odd
  tasks: 
  - name: create remote directory
    file: 
      dest: '{{dest_rep}}'
      state: directory
    tags:
      - init

  - name: create a file on all remote machines
    file:
      dest: '{{all_file}}'
      state: '{{file_state}}'
    tags:
      - init
      - justThis


- name: PLAY FOR DATABASE MACHINES
  hosts: database:&odd
  tasks:
  - name: create a file on the database machines
    file:
      dest: '{{db_file}}'
      state: '{{file_state}}'
    tags:
      - install


- name: PLAY FOR BACKEND MACHINES
  hosts: backend:!even
  tasks:
  - name: create a file on the back-end machines
    file:
      dest: '{{be_file}}'
      state: '{{file_state}}'
    tags:
      - install


- name: PLAY FOR FRONTEND MACHINES
  hosts: frontend:!even
  tasks:
  - name: create a file on the front-end machines
    file:
      dest: '{{fe_file}}'
      state: '{{file_state}}'
    tags:
      - install


- name: WEIRD PLAY 
  hosts: all:&backup:!even:!database
  tasks:
  - name: "create a file on: all:&backup:!even:!database = fe01"
    file:
      dest: '{{weird_file}}'
      state: '{{file_state}}'
    tags:
      - install


- name: BACKUP PLAY
  hosts: backup:&odd
  tasks:
  - name: create a file on the backup machines
    file:
      dest: '{{backup_file}}'
      state: '{{file_state}}'
    tags:
      - install
      - backup


- name: PLAY JUST FOR BE01
  hosts: be01
  tasks:
  - name: create a static file on be01
    file:
      dest: /tmp/ansible/static-file
      state: '{{file_state}}'
    tags:
      - install
      - optional
      - justThis
  - name: create a file on be01
    file:
      dest: '{{be01_file}}'
      state: '{{file_state}}'
    tags:
      - install
      - optional
      - justThis
  - name: create another file on be01
    file:
      dest: '{{another_file}}'
      state: '{{file_state}}'
      #      when: another_file is defined
    tags:
      - install
      - optional


- name: USING TEMPLATES
  hosts: all:&odd
  tasks:
  - name: deploy a simple template file
    template:
      src: templates/template.j2
      dest: '{{dest_rep}}/template.txt'
    tags:
      - create
  - name: destroy the templated file
    file:
      dest: '{{dest_rep}}/template.txt'
      state: absent
    tags:
      - destroy

