---
- name: CREATE A USER 
  hosts: fe01
  tasks:
    - include_role:
        name: create_user
        apply:
          tags:
            - install
      vars:
          user_name: '{{my_install_user}}'
          user_state: '{{user_state}}'
          ssh_key: '{{my_local_pub_key}}'
  become: yes

- name: POPULATE USER ACCOUNT
  hosts: fe01
  tasks:
    - name: create destination folder
      file:
        path: '{{my_dest_dir}}'
        state: directory
      tags:
        - init
      when: user_state == "present"

    - name: copy files
      copy: 
        src: '{{my_src_file}}'
        dest: '{{my_dest_dir}}'
        owner: '{{my_install_user}}'
        group: '{{my_install_user}}'
        mode: '{{my_default_mode}}'
      tags:
        - init
      when: user_state == "present"

  become: yes
