---
- name: CREATE A USER 
  hosts: be01
  become: yes
  tasks:
    - include_role:
        name: create_user
      vars:
          user_name: olivier
          user_state: present
          #ssh_key: ~/.ssh/id_key.pub
