---
- name: INIT TASKS FOR ALL MACHINES
  hosts: all:&odd
  tasks: 
  - name: create remote directory
    file: 
      dest: /tmp/ansible
      state: directory
    tags:
      - init

  - name: create a file on all remote machines
    file:
      dest: /tmp/ansible/ansible
      state: '{{file_state}}'
    tags:
      - init


- name: PLAY FOR DATABASE MACHINES
  hosts: database:&odd
  tasks:
  - name: create a file on the database machines
    file:
      dest: /tmp/ansible/dbfile
      state: '{{file_state}}'
    tags:
      - install


- name: PLAY FOR BACKEND MACHINES
  hosts: backend:!even
  tasks:
  - name: create a file on the back-end machines
    file:
      dest: /tmp/ansible/befile
      state: '{{file_state}}'
    tags:
      - install


- name: PLAY FOR FRONTEND MACHINES
  hosts: frontend:!even
  tasks:
  - name: create a file on the front-end machines
    file:
      dest: /tmp/ansible/fefile
      state: '{{file_state}}'
    tags:
      - install


- name: WEIRD PLAY 
  hosts: all:&backup:!even:!database
  tasks:
  - name: "create a file on: all:&backup:!even:!database = fe01"
    file:
      dest: /tmp/ansible/weirdfile
      state: '{{file_state}}'
    tags:
      - install


- name: BACKUP PLAY
  hosts: backup:&odd
  tasks:
  - name: create a file on the backup machines
    file:
      dest: /tmp/ansible/backupfile
      state: '{{file_state}}'
    tags:
      - install
      - backup


- name: PLAY JUST FOR BE01
  hosts: be01
  tasks:
  - name: create a file on be01
    file:
      dest: /tmp/ansible/be01file
      state: '{{file_state}}'
    tags:
      - install
      - optional


